# Generated by Django 2.2 on 2020-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(default='01715254640', max_length=500),
        ),
    ]
