# Generated by Django 2.2 on 2020-02-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_apply_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(default='cv.txt', upload_to='cv'),
        ),
    ]
