# Generated by Django 2.2 on 2020-02-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200208_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='student_id',
            field=models.FileField(upload_to='id'),
        ),
    ]
